import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Card } from '@/components/ui/card';
import { AlertTriangle, Scale } from 'lucide-react';

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      
      <main className="flex-1 container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="text-center space-y-4">
            <Scale className="h-16 w-16 text-primary mx-auto" />
            <h1 className="text-4xl font-bold text-foreground">Legal Disclaimer</h1>
            <p className="text-lg text-muted-foreground">
              Important information about using Miras
            </p>
          </div>

          <Card className="p-8 border-destructive/50 bg-destructive/5">
            <div className="flex gap-4 mb-4">
              <AlertTriangle className="h-8 w-8 text-destructive flex-shrink-0" />
              <div>
                <h2 className="text-2xl font-bold text-destructive mb-2">
                  CRITICAL: READ BEFORE USING MIRAS
                </h2>
                <p className="text-foreground font-semibold">
                  Miras is an educational tool only. It is NOT a substitute for professional legal or religious advice.
                </p>
              </div>
            </div>
          </Card>

          <div className="space-y-6 text-muted-foreground">
            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">1. No Attorney-Client Relationship</h2>
              <p>
                Use of Miras does not create an attorney-client relationship between you and the creators, developers, 
                or any affiliated parties. Miras does not provide legal advice, and any information generated by the 
                platform should not be relied upon as legal advice.
              </p>
              <p>
                <strong className="text-foreground">You must consult a licensed Illinois estate attorney</strong> before 
                creating, executing, or implementing any estate planning documents or strategies suggested by Miras.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">2. No Religious Authority</h2>
              <p>
                Miras provides calculations based on general Sunni fiqh principles for educational purposes. These 
                calculations are not authoritative Islamic rulings (fatawa) and may not account for:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Individual family circumstances and complexities</li>
                <li>Regional or school-specific fiqh interpretations</li>
                <li>Complex inheritance scenarios (polygamy, estranged heirs, etc.)</li>
                <li>Contemporary scholarly debates or minority opinions</li>
              </ul>
              <p>
                <strong className="text-foreground">You must consult a qualified Islamic scholar</strong> with expertise 
                in inheritance law (fara'id) before implementing any distribution plan based on Miras calculations.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">3. Educational Purpose Only</h2>
              <p>
                All documents, calculations, checklists, and action items generated by Miras are for <strong>educational 
                and informational purposes only</strong>. They are:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>NOT legally binding documents</li>
                <li>NOT suitable for filing with courts or government agencies</li>
                <li>NOT reviewed or approved by attorneys or scholars</li>
                <li>NOT tailored to your specific legal or religious situation</li>
              </ul>
              <p>
                The "Action Packet" and "Sample Will" are illustrative examples only. Do not execute or rely on these 
                documents without professional legal review and customization.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">4. Illinois-Specific Focus</h2>
              <p>
                Miras is designed specifically for residents of Illinois and incorporates Illinois estate law as of 2024. 
                If you reside in another state or country:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Illinois-specific legal information will not apply to you</li>
                <li>You must consult an attorney licensed in your jurisdiction</li>
                <li>State laws on wills, trusts, spousal rights, and probate vary significantly</li>
              </ul>
              <p>
                Even if you live in Illinois, laws change. Always verify current statutes and regulations with a 
                licensed attorney.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">5. No Warranty or Guarantee</h2>
              <p>
                Miras is provided "as is" without any warranties, express or implied. We do not guarantee:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Accuracy or completeness of calculations</li>
                <li>Compliance with current or future laws</li>
                <li>Alignment with all schools of Islamic jurisprudence</li>
                <li>Freedom from errors, bugs, or technical issues</li>
                <li>Fitness for any particular purpose</li>
              </ul>
              <p>
                Users assume all risks associated with using information from Miras. We recommend having all calculations 
                independently verified by professionals.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">6. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, the creators, developers, contributors, and affiliated parties 
                of Miras shall not be liable for any:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Direct, indirect, incidental, or consequential damages</li>
                <li>Loss of property, money, or legal rights</li>
                <li>Errors or omissions in calculations or legal information</li>
                <li>Reliance on information provided by Miras</li>
                <li>Technical failures or data loss</li>
              </ul>
              <p>
                <strong className="text-foreground">You use Miras at your own risk.</strong>
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">7. Privacy and Data Storage</h2>
              <p>
                For this hackathon demonstration version:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>All data is stored locally in your browser (session storage)</li>
                <li>No personally identifiable information (PII) is transmitted to servers</li>
                <li>Data is automatically deleted when you close your browser or clear session storage</li>
                <li>We do not collect, store, or share your personal or family information</li>
              </ul>
              <p>
                <strong className="text-foreground">Important:</strong> Do not use Miras on shared or public computers. 
                Always click "End Session & Wipe Data" when finished to protect your privacy.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">8. Complex Cases Require Expert Review</h2>
              <p>
                Miras uses simplified Sunni fiqh models and cannot handle complex inheritance scenarios such as:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Polygamous marriages</li>
                <li>Estranged or disinherited heirs</li>
                <li>Cross-border estates (assets in multiple countries)</li>
                <li>Blended families with stepchildren</li>
                <li>Disputes among heirs</li>
                <li>Business succession planning</li>
                <li>Special needs beneficiaries</li>
              </ul>
              <p>
                If any of these situations apply to you, <strong className="text-foreground">consult professionals 
                immediately</strong>. Do not rely on Miras alone.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">9. Third-Party Links and Resources</h2>
              <p>
                Miras may provide links to third-party websites, resources, or tools. We do not endorse, control, 
                or assume responsibility for:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Accuracy of third-party information</li>
                <li>Privacy practices of external sites</li>
                <li>Quality of external services or professionals</li>
              </ul>
              <p>
                Always independently verify any third-party information or service providers.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">10. Updates and Changes</h2>
              <p>
                This disclaimer may be updated at any time without notice. Continued use of Miras after changes 
                constitutes acceptance of the updated disclaimer. Laws and fiqh interpretations also evolve—always 
                consult current sources and professionals.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">11. Governing Law</h2>
              <p>
                This disclaimer and your use of Miras are governed by the laws of Illinois, United States, without 
                regard to conflict of law principles. Any disputes shall be resolved in the courts of Illinois.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold text-foreground">12. Contact and Questions</h2>
              <p>
                For questions about this disclaimer or Miras functionality (not legal or religious advice), contact:
              </p>
              <p className="ml-4">
                <strong className="text-foreground">Email:</strong> support@miras.com<br />
                <strong className="text-foreground">Website:</strong> www.miras.com
              </p>
            </section>
          </div>

          <Card className="p-6 bg-destructive/10 border-destructive/30">
            <div className="space-y-3">
              <h3 className="text-xl font-bold text-destructive">By Using Miras, You Acknowledge and Agree:</h3>
              <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
                <li>You have read and understood this entire disclaimer</li>
                <li>Miras is educational only and not legal or religious advice</li>
                <li>You will consult licensed attorneys and qualified scholars before taking action</li>
                <li>You assume all risks and waive all claims against Miras creators and contributors</li>
                <li>You will not execute any documents generated by Miras without professional review</li>
              </ul>
            </div>
          </Card>

          <div className="text-center py-6">
            <p className="text-sm text-muted-foreground italic">
              Last updated: November 2, 2025
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
