import { useState } from 'react';
import { Button } from './ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from './ui/dialog';
import { Checkbox } from './ui/checkbox';
import { AlertTriangle } from 'lucide-react';

interface DisclaimerModalProps {
  open: boolean;
  onAccept: () => void;
  onCancel: () => void;
}

export function DisclaimerModal({ open, onAccept, onCancel }: DisclaimerModalProps) {
  const [checked, setChecked] = useState(false);

  const handleAccept = () => {
    if (checked) {
      onAccept();
    }
  };

  return (
    <Dialog open={open} onOpenChange={(open) => !open && onCancel()}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <AlertTriangle className="h-6 w-6 text-warning" />
            Important — Read before continuing
          </DialogTitle>
        </DialogHeader>
        
        <div className="space-y-4 py-4">
          <div className="rounded-lg border-2 border-warning bg-warning/10 p-4">
            <p className="text-sm leading-relaxed">
              <strong>Miras provides educational guidance and is not a substitute for professional legal or religious advice.</strong>
              {' '}Any Action Packet or sample will generated by Miras is not a legally binding document. 
              You must consult a licensed Illinois estate attorney and a qualified Islamic scholar before implementing any estate plan.
            </p>
          </div>

          <div className="flex items-start space-x-2 pt-4">
            <Checkbox 
              id="disclaimer-check" 
              checked={checked} 
              onCheckedChange={(value) => setChecked(value as boolean)}
            />
            <label
              htmlFor="disclaimer-check"
              className="text-sm leading-relaxed cursor-pointer select-none"
            >
              I understand and will consult an attorney and a scholar before implementing any estate plan.
            </label>
          </div>
        </div>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={onCancel}>
            Cancel
          </Button>
          <Button 
            onClick={handleAccept} 
            disabled={!checked}
            className="min-w-32"
          >
            I accept and continue
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
